replicaCount: 3

image:
  repository: swezwalid/fastapi-app
  tag: latest

service:
  type: ClusterIP
  port: 5000

hpa:
  minReplicas: 3
  maxReplicas: 6
  cpu: 70

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  
  hosts:
    - host: helm.cours-datascientest-1.cloudns.ch  
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - helm.cours-datascientest-1.cloudns.ch
      secretName: fastapi-tls